general:
    method-name: "devicemein"
    input-type: "mixed"
    log-dir: "./logs"

data-ingestion:
    list-datasets:
      - name: "Exp-2_static"
        path: "dataset/Exp-2_static"
        type: "mixed"
        load: no 
      - name: "Exp-2_dynamic"
        path: "dataset/Exp-2_dynamic"
        type: "mixed"
        load: no

data-preprocessing:
    required-data-format: raw
    use-known-devices: no
    train-dataset: "Exp-2_static" 
    test-dataset: "Exp-2_dynamic"
    threshold: 0.1

model-training:
    class-name: "DevicemeinTraining"
    class-path: "framework/eval_modules/devicemein_training.py"  # Relative path to the class file
    train-model: yes # Run the training or use already trained models
    # If the method needs a shell script to run the training. Empty if not.
    cmds: ""
    paths:
      repo: "../reimplementations/devicemein"
      eval-dir: "./evaluation/devicemein"
      model-dir: "./evaluation/devicemein/{}-models" # Path to where the models are stored.
      device-file: "{}/devices.txt" # Path to the file containing device names and mac addresses (for ground truth)

model-testing:
    class-name: "DevicemeinTesting"
    class-path: "framework/eval_modules/devicemein_testing.py"
    report-dir: "./evaluation/devicemein/reports/"