general:
    method-name: "geniotid"
    input-type: "per_device"
    log-dir: "./logs"

data-ingestion:
    list-datasets:
      - name: "TrainData"
        path: "<path-to-train-dataset>"
        type: "per_device"
        load: no
      - name: "TestData"
        path: "<path-to-test-dataset>"
        type: "per_device"
        load: no

data-preprocessing:
    required-data-format: raw # [json, csv] (options)
    use-known-devices: no
    train-dataset: "TrainData"
    test-dataset: "TestData"  # can be different from train_data
    threshold: 0.9

model-training:
    class-name: "GenIoTIDTraining"
    class-path: "framework/eval_modules/geniotid_training.py"  # Relative path to the class file
    train-model: yes # Run the training or use already trained models
    # If the method needs a shell script to run the training. Empty if not.
    cmds: ""
    paths:
      repo: "<path-to-the-code-repository"
      eval-dir: "./evaluation/geniotid"
      model-dir: "./evaluation/geniotid/{}-models" # Path to where the models are stored.
      device-file: "{}/devices.txt" # Path to the file containing device names and mac addresses (for ground truth)

model-testing:
    class-name: "GenIoTIDTesting"
    class-path: "framework/eval_modules/geniotid_testing.py"
    report-dir: "./evaluation/geniotid/reports/"
