general:
    method-name: "IoTSentinel"
    input-type: "per_device"
    log-dir: "./logs"

data-ingestion:
    list-datasets:
      - name: "TrainData"
        path: "<path-to-the-train-dataset"
        type: "per_device"
        load: no # yes = Load the list of pcap files, no = the method will take directory as input
      - name: "TestData"
        path: "<path-to-the-test-dataset"
        type: "per_device"
        load: no # yes = Load the list of pcap files, no = the method will take directory as input

data-preprocessing:
    required-data-format: raw # [json, csv] (options)
    use-known-devices: no # IF you want to only test on devices available in the training data
    train-dataset: "TrainData"  # can be different from train_data
    test-dataset: "TestData"
    threshold: 0.5

model-training:
    class-name: "IoTSentinelTraining"
    class-path: "framework/eval_modules/iot_sentinel_training.py"  # Relative path to the class file
    train-model: yes # Run the training or use already trained models
    # If the method needs a shell script to run the training. Empty if not.
    train-cmd: "" #"sh ./run-mudgee.sh . IoT-Sentinel" # IoT-Sentinel 
    paths:
      repo: "<path-to-the-code-repository>"
      eval-dir: "./evaluation/iot-sentinel"
      model-dir: "./evaluation/iot-sentinel/models" # Path to where the models are stored.

model-testing:
    class-name: "IoTSentinelTesting"
    class-path: "framework/eval_modules/iot_sentinel_testing.py"
    report-dir: "./evaluation/iot-sentinel/reports/"
